server:
  port: 18081
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 102MB
  application:
    name: goods
  profiles:
    active:
      jdbc,eureka

#feign:
#  hystrix:
#    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.changgou.goods.pojo

logging:
  level:
    com.changgou.goods: warn

