server:
  port: 20001
spring:
  application:
    name: gateway-web
  profiles:
    active:
      eureka
  redis:
    host: 10.211.55.3
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: changgou_goods_route
          uri: lb://goods
          predicates:
            - Path=/api/brand/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: changgou_auth_route
          uri: lb://user-auth
          predicates:
            - Path=/api/login/**
          filters:
            - StripPrefix=1
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

